services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"   # <-- expõe o banco na porta local 5432
volumes:
  pgdata:
